pokemons = [
    {
        "name": "Bulbasaur",
        "hp": 294,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 1 / 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Solar Beam", "move_type": "Grass", "power": 120},
            {"move": "Power Whip", "move_type": "Grass", "power": 120},
            {"move": "Take Down", "move_type": "Normal", "power": 90},
            {"move": "Seed Bomb", "move_type": "Grass", "power": 80},
        ],
    },
    {
        "name": "Ivysaur",
        "hp": 324,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 1 / 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Solar Beam", "move_type": "Grass", "power": 120},
            {"move": "Power Whip", "move_type": "Grass", "power": 120},
            {"move": "Take Down", "move_type": "Normal", "power": 90},
            {"move": "Seed Bomb", "move_type": "Grass", "power": 80},
        ],
    },
    {
        "name": "Venusaur",
        "hp": 364,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 1 / 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Solar Beam", "move_type": "Grass", "power": 120},
            {"move": "Power Whip", "move_type": "Grass", "power": 120},
            {"move": "Petal Dance", "move_type": "Grass", "power": 120},
            {"move": "Take Down", "move_type": "Normal", "power": 90},
        ],
    },
    {
        "name": "Charmander",
        "hp": 282,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 1 / 2},
            {"pokemon_type": "Water", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Ice", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Flare Blitz", "move_type": "Fire", "power": 120},
            {"move": "Inferno", "move_type": "Fire", "power": 100},
            {"move": "Flamethrower", "move_type": "Fire", "power": 90},
            {"move": "Slash", "move_type": "Normal", "power": 70},
        ],
    },
    {
        "name": "Charmeleon",
        "hp": 320,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 1 / 2},
            {"pokemon_type": "Water", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Ice", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Flare Blitz", "move_type": "Fire", "power": 120},
            {"move": "Inferno", "move_type": "Fire", "power": 100},
            {"move": "Flamethrower", "move_type": "Fire", "power": 90},
            {"move": "Slash", "move_type": "Normal", "power": 70},
        ],
    },
    {
        "name": "Charizard",
        "hp": 360,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 1 / 2},
            {"pokemon_type": "Water", "multiplier": 2},
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 0},
            {"pokemon_type": "Bug", "multiplier": 1 / 4},
            {"pokemon_type": "Rock", "multiplier": 4},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Flare Blitz", "move_type": "Fire", "power": 120},
            {"move": "Inferno", "move_type": "Fire", "power": 100},
            {"move": "Heat Wave", "move_type": "Fire", "power": 95},
            {"move": "Flamethrower", "move_type": "Fire", "power": 90},
        ],
    },
    {
        "name": "Squirtle",
        "hp": 292,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 1 / 2},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 2},
            {"pokemon_type": "Ice", "multiplier": 1 / 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Wave Crash", "move_type": "Water", "power": 120},
            {"move": "Hydro Pump", "move_type": "Water", "power": 110},
            {"move": "Aqua Tail", "move_type": "Water", "power": 90},
            {"move": "Water Pulse", "move_type": "Water", "power": 60},
        ],
    },
    {
        "name": "Wartortle",
        "hp": 322,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 1 / 2},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 2},
            {"pokemon_type": "Ice", "multiplier": 1 / 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Wave Crash", "move_type": "Water", "power": 120},
            {"move": "Hydro Pump", "move_type": "Water", "power": 110},
            {"move": "Aqua Tail", "move_type": "Water", "power": 90},
            {"move": "Water Pulse", "move_type": "Water", "power": 60},
        ],
    },
    {
        "name": "Blastoise",
        "hp": 362,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 1 / 2},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 2},
            {"pokemon_type": "Ice", "multiplier": 1 / 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Wave Crash", "move_type": "Water", "power": 120},
            {"move": "Hydro Pump", "move_type": "Water", "power": 110},
            {"move": "Aqua Tail", "move_type": "Water", "power": 90},
            {"move": "Water Pulse", "move_type": "Water", "power": 60},
        ],
    },
    {
        "name": "Caterpie",
        "hp": 294,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Rock", "multiplier": 2},
        ],
        "moves": [
            {"move": "Bug Bite", "move_type": "Bug", "power": 60},
            {"move": "Electroweb", "move_type": "Electric", "power": 55},
            {"move": "Tackle", "move_type": "Normal", "power": 40},
            {"move": "Snore", "move_type": "Normal", "power": 40},
        ],
    },
    {
        "name": "Metapod",
        "hp": 304,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Rock", "multiplier": 2},
        ],
        "moves": [
            {"move": "Bug Bite", "move_type": "Bug", "power": 60},
            {"move": "Electroweb", "move_type": "Electric", "power": 55},
            {"move": "Tackle", "move_type": "Normal", "power": 40},
            {"move": "Snore", "move_type": "Normal", "power": 40},
        ],
    },
    {
        "name": "Butterfree",
        "hp": 324,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 4},
            {"pokemon_type": "Ground", "multiplier": 0},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 4},
        ],
        "moves": [
            {"move": "Bug Buzz", "move_type": "Bug", "power": 90},
            {"move": "Air Slash", "move_type": "Flying", "power": 75},
            {"move": "Psybeam", "move_type": "Psychic", "power": 65},
            {"move": "Bug Bite", "move_type": "Bug", "power": 60},
        ],
    },
    {
        "name": "Weedle",
        "hp": 284,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Fighting", "multiplier": 1 / 4},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Bug Bite", "move_type": "Bug", "power": 60},
            {"move": "Electroweb", "move_type": "Electric", "power": 55},
            {"move": "Tackle", "move_type": "Normal", "power": 40},
            {"move": "Poison Sting", "move_type": "Poison", "power": 15},
        ],
    },
    {
        "name": "Kakuna",
        "hp": 294,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Fighting", "multiplier": 1 / 4},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Bug Bite", "move_type": "Bug", "power": 60},
            {"move": "Electroweb", "move_type": "Electric", "power": 55},
            {"move": "Tackle", "move_type": "Normal", "power": 40},
            {"move": "Poison Sting", "move_type": "Poison", "power": 15},
        ],
    },
    {
        "name": "Beedrill",
        "hp": 334,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Fighting", "multiplier": 1 / 4},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Poison Jab", "move_type": "Poison", "power": 80},
            {"move": "Venoshock", "move_type": "Poison", "power": 65},
            {"move": "Assurance", "move_type": "Dark", "power": 60},
            {"move": "Bug Bite", "move_type": "Bug", "power": 60},
        ],
    },
    {
        "name": "Pidgey",
        "hp": 284,
        "defenses": [
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Ground", "multiplier": 0},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Ghost", "multiplier": 0},
        ],
        "moves": [
            {"move": "Hurricane", "move_type": "Flying", "power": 110},
            {"move": "Air Slash", "move_type": "Flying", "power": 75},
            {"move": "Aerial Ace", "move_type": "Flying", "power": 60},
            {"move": "Wing Attack", "move_type": "Flying", "power": 60},
        ],
    },
    {
        "name": "Pidgeotto",
        "hp": 330,
        "defenses": [
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Ground", "multiplier": 0},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Ghost", "multiplier": 0},
        ],
        "moves": [
            {"move": "Hurricane", "move_type": "Flying", "power": 110},
            {"move": "Air Slash", "move_type": "Flying", "power": 75},
            {"move": "Aerial Ace", "move_type": "Flying", "power": 60},
            {"move": "Wing Attack", "move_type": "Flying", "power": 60},
        ],
    },
    {
        "name": "Pidgeot",
        "hp": 370,
        "defenses": [
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Ground", "multiplier": 0},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Ghost", "multiplier": 0},
        ],
        "moves": [
            {"move": "Hurricane", "move_type": "Flying", "power": 110},
            {"move": "Air Slash", "move_type": "Flying", "power": 75},
            {"move": "Aerial Ace", "move_type": "Flying", "power": 60},
            {"move": "Wing Attack", "move_type": "Flying", "power": 60},
        ],
    },
    {
        "name": "Rattata",
        "hp": 264,
        "defenses": [
            {"pokemon_type": "Fighting", "multiplier": 2},
            {"pokemon_type": "Ghost", "multiplier": 0},
        ],
        "moves": [
            {"move": "Double-Edge", "move_type": "Normal", "power": 120},
            {"move": "Take Down", "move_type": "Normal", "power": 90},
            {"move": "Crunch", "move_type": "Dark", "power": 80},
            {"move": "Sucker Punch", "move_type": "Dark", "power": 70},
        ],
    },
    {
        "name": "Raticate",
        "hp": 314,
        "defenses": [
            {"pokemon_type": "Fighting", "multiplier": 2},
            {"pokemon_type": "Ghost", "multiplier": 0},
        ],
        "moves": [
            {"move": "Double-Edge", "move_type": "Normal", "power": 120},
            {"move": "Take Down", "move_type": "Normal", "power": 90},
            {"move": "Crunch", "move_type": "Dark", "power": 80},
            {"move": "Sucker Punch", "move_type": "Dark", "power": 70},
        ],
    },
    {
        "name": "Spearow",
        "hp": 284,
        "defenses": [
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Ground", "multiplier": 0},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Ghost", "multiplier": 0},
        ],
        "moves": [
            {"move": "Take Down", "move_type": "Normal", "power": 90},
            {"move": "Drill Peck", "move_type": "Flying", "power": 80},
            {"move": "Aerial Ace", "move_type": "Flying", "power": 60},
            {"move": "Wing Attack", "move_type": "Flying", "power": 60},
        ],
    },
    {
        "name": "Fearow",
        "hp": 334,
        "defenses": [
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Ground", "multiplier": 0},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Ghost", "multiplier": 0},
        ],
        "moves": [
            {"move": "Take Down", "move_type": "Normal", "power": 90},
            {"move": "Drill Peck", "move_type": "Flying", "power": 80},
            {"move": "Drill Run", "move_type": "Ground", "power": 80},
            {"move": "Aerial Ace", "move_type": "Flying", "power": 60},
        ],
    },
    {
        "name": "Ekans",
        "hp": 274,
        "defenses": [
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Gunk Shot", "move_type": "Poison", "power": 120},
            {"move": "Belch", "move_type": "Poison", "power": 120},
            {"move": "Sludge Bomb", "move_type": "Poison", "power": 90},
            {"move": "Bite", "move_type": "Dark", "power": 60},
        ],
    },
    {
        "name": "Arbok",
        "hp": 324,
        "defenses": [
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Gunk Shot", "move_type": "Poison", "power": 120},
            {"move": "Belch", "move_type": "Poison", "power": 120},
            {"move": "Sludge Bomb", "move_type": "Poison", "power": 90},
            {"move": "Thunder Fang", "move_type": "Electric", "power": 65},
        ],
    },
    {
        "name": "Pikachu",
        "hp": 274,
        "defenses": [
            {"pokemon_type": "Electric", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Flying", "multiplier": 1 / 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Thunder", "move_type": "Electric", "power": 110},
            {"move": "Iron Tail", "move_type": "Steel", "power": 100},
            {"move": "Thunderbolt", "move_type": "Electric", "power": 90},
            {"move": "Discharge", "move_type": "Electric", "power": 80},
        ],
    },
    {
        "name": "Raichu",
        "hp": 324,
        "defenses": [
            {"pokemon_type": "Electric", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Flying", "multiplier": 1 / 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Thunder", "move_type": "Electric", "power": 110},
            {"move": "Iron Tail", "move_type": "Steel", "power": 100},
            {"move": "Thunderbolt", "move_type": "Electric", "power": 90},
            {"move": "Discharge", "move_type": "Electric", "power": 80},
        ],
    },
    {
        "name": "Sandshrew",
        "hp": 304,
        "defenses": [
            {"pokemon_type": "Water", "multiplier": 2},
            {"pokemon_type": "Electric", "multiplier": 0},
            {"pokemon_type": "Grass", "multiplier": 2},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Earthquake", "move_type": "Ground", "power": 100},
            {"move": "Dig", "move_type": "Ground", "power": 80},
            {"move": "Slash", "move_type": "Normal", "power": 70},
            {"move": "Swift", "move_type": "Normal", "power": 60},
        ],
    },
    {
        "name": "Sandslash",
        "hp": 354,
        "defenses": [
            {"pokemon_type": "Water", "multiplier": 2},
            {"pokemon_type": "Electric", "multiplier": 0},
            {"pokemon_type": "Grass", "multiplier": 2},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Earthquake", "move_type": "Ground", "power": 100},
            {"move": "Dig", "move_type": "Ground", "power": 80},
            {"move": "Crush Claw", "move_type": "Normal", "power": 75},
            {"move": "Slash", "move_type": "Normal", "power": 70},
        ],
    },
    {
        "name": "Nidoran Female",
        "hp": 314,
        "defenses": [
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Earth Power", "move_type": "Ground", "power": 90},
            {"move": "Crunch", "move_type": "Dark", "power": 80},
            {"move": "Bite", "move_type": "Dark", "power": 60},
            {"move": "Scratch", "move_type": "Normal", "power": 40},
        ],
    },
    {
        "name": "Nidorina",
        "hp": 344,
        "defenses": [
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Earth Power", "move_type": "Ground", "power": 90},
            {"move": "Crunch", "move_type": "Dark", "power": 80},
            {"move": "Bite", "move_type": "Dark", "power": 60},
            {"move": "Scratch", "move_type": "Normal", "power": 40},
        ],
    },
    {
        "name": "Nidoqueen",
        "hp": 384,
        "defenses": [
            {"pokemon_type": "Water", "multiplier": 2},
            {"pokemon_type": "Electric", "multiplier": 0},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Poison", "multiplier": 1 / 4},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Superpower", "move_type": "Fighting", "power": 120},
            {"move": "Sludge Wave", "move_type": "Poison", "power": 95},
            {"move": "Earth Power", "move_type": "Ground", "power": 90},
            {"move": "Crunch", "move_type": "Dark", "power": 80},
        ],
    },
    {
        "name": "Nidoran Male",
        "hp": 296,
        "defenses": [
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Earth Power", "move_type": "Ground", "power": 90},
            {"move": "Poison Jab", "move_type": "Poison", "power": 80},
            {"move": "Horn Attack", "move_type": "Normal", "power": 65},
            {"move": "Peck", "move_type": "Flying", "power": 35},
        ],
    },
    {
        "name": "Nidorino",
        "hp": 326,
        "defenses": [
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Earth Power", "move_type": "Ground", "power": 90},
            {"move": "Poison Jab", "move_type": "Poison", "power": 80},
            {"move": "Horn Attack", "move_type": "Normal", "power": 65},
            {"move": "Peck", "move_type": "Flying", "power": 35},
        ],
    },
    {
        "name": "Nidoking",
        "hp": 366,
        "defenses": [
            {"pokemon_type": "Water", "multiplier": 2},
            {"pokemon_type": "Electric", "multiplier": 0},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Poison", "multiplier": 1 / 4},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Megahorn", "move_type": "Bug", "power": 120},
            {"move": "Sludge Wave", "move_type": "Poison", "power": 95},
            {"move": "Earth Power", "move_type": "Ground", "power": 90},
            {"move": "Poison Jab", "move_type": "Poison", "power": 80},
        ],
    },
    {
        "name": "Clefairy",
        "hp": 344,
        "defenses": [
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Poison", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Dragon", "multiplier": 0},
            {"pokemon_type": "Dark", "multiplier": 1 / 2},
            {"pokemon_type": "Steel", "multiplier": 2},
        ],
        "moves": [
            {"move": "Moonblast", "move_type": "Fairy", "power": 95},
            {"move": "Meteor Mash", "move_type": "Steel", "power": 90},
            {"move": "Pound", "move_type": "Normal", "power": 40},
            {"move": "Disarming Voice", "move_type": "Fairy", "power": 40},
        ],
    },
    {
        "name": "Clefable",
        "hp": 394,
        "defenses": [
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Poison", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Dragon", "multiplier": 0},
            {"pokemon_type": "Dark", "multiplier": 1 / 2},
            {"pokemon_type": "Steel", "multiplier": 2},
        ],
        "moves": [
            {"move": "Moonblast", "move_type": "Fairy", "power": 95},
            {"move": "Meteor Mash", "move_type": "Steel", "power": 90},
            {"move": "Pound", "move_type": "Normal", "power": 40},
            {"move": "Disarming Voice", "move_type": "Fairy", "power": 40},
        ],
    },
    {
        "name": "Vulpix",
        "hp": 280,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 0},
            {"pokemon_type": "Water", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Ice", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Fire Blast", "move_type": "Fire", "power": 110},
            {"move": "Inferno", "move_type": "Fire", "power": 100},
            {"move": "Flamethrower", "move_type": "Fire", "power": 90},
            {"move": "Extrasensory", "move_type": "Psychic", "power": 80},
        ],
    },
    {
        "name": "Ninetales",
        "hp": 350,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 0},
            {"pokemon_type": "Water", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Ice", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Fire Blast", "move_type": "Fire", "power": 110},
            {"move": "Inferno", "move_type": "Fire", "power": 100},
            {"move": "Flamethrower", "move_type": "Fire", "power": 90},
            {"move": "Extrasensory", "move_type": "Psychic", "power": 80},
        ],
    },
    {
        "name": "Jigglypuff",
        "hp": 434,
        "defenses": [
            {"pokemon_type": "Poison", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Ghost", "multiplier": 0},
            {"pokemon_type": "Dragon", "multiplier": 0},
            {"pokemon_type": "Dark", "multiplier": 1 / 2},
            {"pokemon_type": "Steel", "multiplier": 2},
        ],
        "moves": [
            {"move": "Double-Edge", "move_type": "Normal", "power": 120},
            {"move": "Hyper Voice", "move_type": "Normal", "power": 90},
            {"move": "Body Slam", "move_type": "Normal", "power": 85},
            {"move": "Round", "move_type": "Normal", "power": 60},
        ],
    },
    {
        "name": "Wigglytuff",
        "hp": 484,
        "defenses": [
            {"pokemon_type": "Poison", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Ghost", "multiplier": 0},
            {"pokemon_type": "Dragon", "multiplier": 0},
            {"pokemon_type": "Dark", "multiplier": 1 / 2},
            {"pokemon_type": "Steel", "multiplier": 2},
        ],
        "moves": [
            {"move": "Double-Edge", "move_type": "Normal", "power": 120},
            {"move": "Hyper Voice", "move_type": "Normal", "power": 90},
            {"move": "Play Rough", "move_type": "Fairy", "power": 90},
            {"move": "Body Slam", "move_type": "Normal", "power": 85},
        ],
    },
    {
        "name": "Zubat",
        "hp": 284,
        "defenses": [
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 4},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 0},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 4},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Leech Life", "move_type": "Bug", "power": 80},
            {"move": "Air Slash", "move_type": "Flying", "power": 75},
            {"move": "Venoshock", "move_type": "Poison", "power": 65},
            {"move": "Bite", "move_type": "Dark", "power": 60},
        ],
    },
    {
        "name": "Golbat",
        "hp": 354,
        "defenses": [
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 4},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 0},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 4},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Leech Life", "move_type": "Bug", "power": 80},
            {"move": "Air Slash", "move_type": "Flying", "power": 75},
            {"move": "Venoshock", "move_type": "Poison", "power": 65},
            {"move": "Bite", "move_type": "Dark", "power": 60},
        ],
    },
    {
        "name": "Oddish",
        "hp": 294,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 1 / 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Petal Dance", "move_type": "Grass", "power": 120},
            {"move": "Moonblast", "move_type": "Fairy", "power": 95},
            {"move": "Giga Drain", "move_type": "Grass", "power": 75},
            {"move": "Mega Drain", "move_type": "Grass", "power": 40},
        ],
    },
    {
        "name": "Gloom",
        "hp": 324,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 1 / 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Petal Dance", "move_type": "Grass", "power": 120},
            {"move": "Moonblast", "move_type": "Fairy", "power": 95},
            {"move": "Giga Drain", "move_type": "Grass", "power": 75},
            {"move": "Mega Drain", "move_type": "Grass", "power": 40},
        ],
    },
    {
        "name": "Vileplume",
        "hp": 354,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 1 / 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Petal Dance", "move_type": "Grass", "power": 120},
            {"move": "Moonblast", "move_type": "Fairy", "power": 95},
            {"move": "Giga Drain", "move_type": "Grass", "power": 75},
            {"move": "Mega Drain", "move_type": "Grass", "power": 40},
        ],
    },
    {
        "name": "Paras",
        "hp": 274,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 4},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 1 / 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Poison", "multiplier": 2},
            {"pokemon_type": "Ground", "multiplier": 1 / 4},
            {"pokemon_type": "Flying", "multiplier": 4},
            {"pokemon_type": "Bug", "multiplier": 2},
            {"pokemon_type": "Rock", "multiplier": 2},
        ],
        "moves": [
            {"move": "X-Scissor", "move_type": "Bug", "power": 80},
            {"move": "Giga Drain", "move_type": "Grass", "power": 75},
            {"move": "Slash", "move_type": "Normal", "power": 70},
            {"move": "Fury Cutter", "move_type": "Bug", "power": 40},
        ],
    },
    {
        "name": "Parasect",
        "hp": 324,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 4},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 1 / 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Poison", "multiplier": 2},
            {"pokemon_type": "Ground", "multiplier": 1 / 4},
            {"pokemon_type": "Flying", "multiplier": 4},
            {"pokemon_type": "Bug", "multiplier": 2},
            {"pokemon_type": "Rock", "multiplier": 2},
        ],
        "moves": [
            {"move": "X-Scissor", "move_type": "Bug", "power": 80},
            {"move": "Giga Drain", "move_type": "Grass", "power": 75},
            {"move": "Slash", "move_type": "Normal", "power": 70},
            {"move": "Cross Poison", "move_type": "Poison", "power": 70},
        ],
    },
    {
        "name": "Venonat",
        "hp": 324,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Fighting", "multiplier": 1 / 4},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Psychic", "move_type": "Psychic", "power": 90},
            {"move": "Bug Buzz", "move_type": "Bug", "power": 90},
            {"move": "Zen Headbutt", "move_type": "Psychic", "power": 80},
            {"move": "Leech Life", "move_type": "Bug", "power": 80},
        ],
    },
    {
        "name": "Venomoth",
        "hp": 344,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Fighting", "multiplier": 1 / 4},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Fairy", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Psychic", "move_type": "Psychic", "power": 90},
            {"move": "Bug Buzz", "move_type": "Bug", "power": 90},
            {"move": "Zen Headbutt", "move_type": "Psychic", "power": 80},
            {"move": "Leech Life", "move_type": "Bug", "power": 80},
        ],
    },
    {
        "name": "Diglett",
        "hp": 224,
        "defenses": [
            {"pokemon_type": "Water", "multiplier": 2},
            {"pokemon_type": "Electric", "multiplier": 0},
            {"pokemon_type": "Grass", "multiplier": 2},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Earthquake", "move_type": "Ground", "power": 100},
            {"move": "Earth Power", "move_type": "Ground", "power": 90},
            {"move": "Dig", "move_type": "Ground", "power": 80},
            {"move": "Slash", "move_type": "Normal", "power": 70},
        ],
    },
    {
        "name": "Dugtrio",
        "hp": 274,
        "defenses": [
            {"pokemon_type": "Water", "multiplier": 2},
            {"pokemon_type": "Electric", "multiplier": 0},
            {"pokemon_type": "Grass", "multiplier": 2},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Poison", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Earthquake", "move_type": "Ground", "power": 100},
            {"move": "Earth Power", "move_type": "Ground", "power": 90},
            {"move": "Dig", "move_type": "Ground", "power": 80},
            {"move": "Tri Attack", "move_type": "Normal", "power": 80},
        ],
    },
    {
        "name": "Meowth",
        "hp": 284,
        "defenses": [
            {"pokemon_type": "Fighting", "multiplier": 2},
            {"pokemon_type": "Ghost", "multiplier": 0},
        ],
        "moves": [
            {"move": "Play Rough", "move_type": "Fairy", "power": 90},
            {"move": "Slash", "move_type": "Normal", "power": 70},
            {"move": "Assurance", "move_type": "Dark", "power": 60},
            {"move": "Bite", "move_type": "Dark", "power": 60},
        ],
    },
    {
        "name": "Persian",
        "hp": 334,
        "defenses": [
            {"pokemon_type": "Fighting", "multiplier": 2},
            {"pokemon_type": "Ghost", "multiplier": 0},
        ],
        "moves": [
            {"move": "Play Rough", "move_type": "Fairy", "power": 90},
            {"move": "Slash", "move_type": "Normal", "power": 70},
            {"move": "Assurance", "move_type": "Dark", "power": 60},
            {"move": "Bite", "move_type": "Dark", "power": 60},
        ],
    },
    {
        "name": "Psyduck",
        "hp": 304,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 1 / 2},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 2},
            {"pokemon_type": "Ice", "multiplier": 1 / 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Aqua Tail", "move_type": "Water", "power": 90},
            {"move": "Zen Headbutt", "move_type": "Psychic", "power": 80},
            {"move": "Water Pulse", "move_type": "Water", "power": 60},
            {"move": "Confusion", "move_type": "Psychic", "power": 50},
        ],
    },
    {
        "name": "Golduck",
        "hp": 364,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 1 / 2},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 2},
            {"pokemon_type": "Ice", "multiplier": 1 / 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Hydro Pump", "move_type": "Water", "power": 110},
            {"move": "Aqua Tail", "move_type": "Water", "power": 90},
            {"move": "Zen Headbutt", "move_type": "Psychic", "power": 80},
            {"move": "Water Pulse", "move_type": "Water", "power": 60},
        ],
    },
    {
        "name": "Mankey",
        "hp": 284,
        "defenses": [
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 1 / 2},
            {"pokemon_type": "Dark", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "multiplier": 2},
        ],
        "moves": [
            {"move": "Outrage", "move_type": "Dragon", "power": 120},
            {"move": "Close Combat", "move_type": "Fighting", "power": 120},
            {"move": "Thrash", "move_type": "Normal", "power": 120},
            {"move": "Cross Chop", "move_type": "Fighting", "power": 100},
        ],
    },
    {
        "name": "Primeape",
        "hp": 334,
        "defenses": [
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 1 / 2},
            {"pokemon_type": "Dark", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "multiplier": 2},
        ],
        "moves": [
            {"move": "Outrage", "move_type": "Dragon", "power": 120},
            {"move": "Close Combat", "move_type": "Fighting", "power": 120},
            {"move": "Thrash", "move_type": "Normal", "power": 120},
            {"move": "Cross Chop", "move_type": "Fighting", "power": 100},
        ],
    },
    {
        "name": "Growlithe",
        "hp": 314,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 1 / 2},
            {"pokemon_type": "Water", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Ice", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Flare Blitz", "move_type": "Fire", "power": 120},
            {"move": "Play Rough", "move_type": "Fairy", "power": 90},
            {"move": "Flamethrower", "move_type": "Fire", "power": 90},
            {"move": "Take Down", "move_type": "Normal", "power": 90},
        ],
    },
    {
        "name": "Arcanine",
        "hp": 384,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 1 / 2},
            {"pokemon_type": "Water", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 2},
            {"pokemon_type": "Ice", "multiplier": 1 / 2},
            {"pokemon_type": "Ground", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Flare Blitz", "move_type": "Fire", "power": 120},
            {"move": "Play Rough", "move_type": "Fairy", "power": 90},
            {"move": "Flamethrower", "move_type": "Fire", "power": 90},
            {"move": "Take Down", "move_type": "Normal", "power": 90},
        ],
    },
    {
        "name": "Poliwag",
        "hp": 284,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 1 / 2},
            {"pokemon_type": "Water", "multiplier": 0},
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 2},
            {"pokemon_type": "Ice", "multiplier": 1 / 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Double-Edge", "move_type": "Normal", "power": 120},
            {"move": "Hydro Pump", "move_type": "Water", "power": 110},
            {"move": "Earth Power", "move_type": "Ground", "power": 90},
            {"move": "Body Slam", "move_type": "Normal", "power": 85},
        ],
    },
    {
        "name": "Poliwhirl",
        "hp": 334,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 1 / 2},
            {"pokemon_type": "Water", "multiplier": 0},
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 2},
            {"pokemon_type": "Ice", "multiplier": 1 / 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
        ],
        "moves": [
            {"move": "Double-Edge", "move_type": "Normal", "power": 120},
            {"move": "Hydro Pump", "move_type": "Water", "power": 110},
            {"move": "Earth Power", "move_type": "Ground", "power": 90},
            {"move": "Body Slam", "move_type": "Normal", "power": 85},
        ],
    },
    {
        "name": "Poliwrath",
        "hp": 384,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 1 / 2},
            {"pokemon_type": "Water", "multiplier": 0},
            {"pokemon_type": "Electric", "multiplier": 2},
            {"pokemon_type": "Grass", "multiplier": 2},
            {"pokemon_type": "Ice", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 1 / 2},
            {"pokemon_type": "Dark", "multiplier": 1 / 2},
            {"pokemon_type": "Steel", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "multiplier": 2},
        ],
        "moves": [
            {"move": "Double-Edge", "move_type": "Normal", "power": 120},
            {"move": "Hydro Pump", "move_type": "Water", "power": 110},
            {"move": "Earth Power", "move_type": "Ground", "power": 90},
            {"move": "Body Slam", "move_type": "Normal", "power": 85},
        ],
    },
    {
        "name": "Abra",
        "hp": 254,
        "defenses": [
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Psychic", "multiplier": 1 / 2},
            {"pokemon_type": "Bug", "multiplier": 2},
            {"pokemon_type": "Ghost", "multiplier": 2},
            {"pokemon_type": "Dark", "multiplier": 2},
        ],
        "moves": [
            {"move": "Thunder Punch", "move_type": "Electric", "power": 75},
            {"move": "Ice Punch", "move_type": "Ice", "power": 75},
            {"move": "Fire Punch", "move_type": "Fire", "power": 75},
            {"move": "Knock Off", "move_type": "Dark", "power": 65},
        ],
    },
    {
        "name": "Kadabra",
        "hp": 284,
        "defenses": [
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Psychic", "multiplier": 1 / 2},
            {"pokemon_type": "Bug", "multiplier": 2},
            {"pokemon_type": "Ghost", "multiplier": 2},
            {"pokemon_type": "Dark", "multiplier": 2},
        ],
        "moves": [
            {"move": "Future Sight", "move_type": "Psychic", "power": 120},
            {"move": "Psychic", "move_type": "Psychic", "power": 90},
            {"move": "Psyshock", "move_type": "Psychic", "power": 80},
            {"move": "Psycho Cut", "move_type": "Psychic", "power": 70},
        ],
    },
    {
        "name": "Alakazam",
        "hp": 314,
        "defenses": [
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Psychic", "multiplier": 1 / 2},
            {"pokemon_type": "Bug", "multiplier": 2},
            {"pokemon_type": "Ghost", "multiplier": 2},
            {"pokemon_type": "Dark", "multiplier": 2},
        ],
        "moves": [
            {"move": "Future Sight", "move_type": "Psychic", "power": 120},
            {"move": "Psychic", "move_type": "Psychic", "power": 90},
            {"move": "Psyshock", "move_type": "Psychic", "power": 80},
            {"move": "Psycho Cut", "move_type": "Psychic", "power": 70},
        ],
    },
    {
        "name": "Machop",
        "hp": 344,
        "defenses": [
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 1 / 2},
            {"pokemon_type": "Dark", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "multiplier": 2},
        ],
        "moves": [
            {"move": "Double-Edge", "move_type": "Normal", "power": 120},
            {"move": "Cross Chop", "move_type": "Fighting", "power": 100},
            {"move": "Dynamic Punch", "move_type": "Fighting", "power": 100},
            {"move": "Strength", "move_type": "Normal", "power": 80},
        ],
    },
    {
        "name": "Machoke",
        "hp": 364,
        "defenses": [
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 1 / 2},
            {"pokemon_type": "Dark", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "multiplier": 2},
        ],
        "moves": [
            {"move": "Double-Edge", "move_type": "Normal", "power": 120},
            {"move": "Cross Chop", "move_type": "Fighting", "power": 100},
            {"move": "Dynamic Punch", "move_type": "Fighting", "power": 100},
            {"move": "Strength", "move_type": "Normal", "power": 80},
        ],
    },
    {
        "name": "Machamp",
        "hp": 384,
        "defenses": [
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Bug", "multiplier": 1 / 2},
            {"pokemon_type": "Rock", "multiplier": 1 / 2},
            {"pokemon_type": "Dark", "multiplier": 1 / 2},
            {"pokemon_type": "Fairy", "multiplier": 2},
        ],
        "moves": [
            {"move": "Double-Edge", "move_type": "Normal", "power": 120},
            {"move": "Cross Chop", "move_type": "Fighting", "power": 100},
            {"move": "Dynamic Punch", "move_type": "Fighting", "power": 100},
            {"move": "Strength", "move_type": "Normal", "power": 80},
        ],
    },
    {
        "name": "Bellsprout",
        "hp": 304,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 1 / 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Power Whip", "move_type": "Grass", "power": 120},
            {"move": "Slam", "move_type": "Normal", "power": 80},
            {"move": "Poison Jab", "move_type": "Poison", "power": 80},
            {"move": "Knock Off", "move_type": "Dark", "power": 65},
        ],
    },
    {
        "name": "Weepinbell",
        "hp": 334,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 1 / 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Power Whip", "move_type": "Grass", "power": 120},
            {"move": "Slam", "move_type": "Normal", "power": 80},
            {"move": "Poison Jab", "move_type": "Poison", "power": 80},
            {"move": "Knock Off", "move_type": "Dark", "power": 65},
        ],
    },
    {
        "name": "Victreebel",
        "hp": 364,
        "defenses": [
            {"pokemon_type": "Fire", "multiplier": 2},
            {"pokemon_type": "Water", "multiplier": 1 / 2},
            {"pokemon_type": "Electric", "multiplier": 1 / 2},
            {"pokemon_type": "Grass", "multiplier": 1 / 4},
            {"pokemon_type": "Ice", "multiplier": 2},
            {"pokemon_type": "Fighting", "multiplier": 1 / 2},
            {"pokemon_type": "Flying", "multiplier": 2},
            {"pokemon_type": "Psychic", "multiplier": 2},
            {"pokemon_type": "Fairy", "percentage": 1 / 2},
        ],
        "moves": [
            {"move": "Leaf Storm", "move_type": "Grass", "power": 130},
            {"move": "Power Whip", "move_type": "Grass", "power": 120},
            {"move": "Leaf Blade", "move_type": "Grass", "power": 90},
            {"move": "Razor Leaf", "move_type": "Grass", "power": 55},
        ],
    },
]
