pokemons = [
    {
        "name": "Bulbasaur",
        "hp": 294,
        "moves": [
            {"move": "Solar Beam", "move_type": "Grass", "power": 120},
            {"move": "Power Whip", "move_type": "Grass", "power": 120},
            {"move": "Take Down", "move_type": "Normal", "power": 90},
            {"move": "Seed Bomb", "move_type": "Grass", "power": 80},
        ],
        "strengths": [
            {"pokemon_type": "Water", "percentage": 0.5},
            {"pokemon_type": "Electric", "percentage": 0.5},
            {"pokemon_type": "Grass", "percentage": 0.75},
            {"pokemon_type": "Fighting", "percentage": 0.5},
            {"pokemon_type": "Fairy", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Fire", "percentage": 2},
            {"pokemon_type": "Ice", "percentage": 2},
            {"pokemon_type": "Flying", "percentage": 2},
            {"pokemon_type": "Psychic", "percentage": 2},
        ],
    },
    {
        "name": "Ivysaur",
        "hp": 324,
        "moves": [
            {"move": "Solar Beam", "move_type": "Grass", "power": 120},
            {"move": "Power Whip", "move_type": "Grass", "power": 120},
            {"move": "Take Down", "move_type": "Normal", "power": 90},
            {"move": "Seed Bomb", "move_type": "Grass", "power": 80},
        ],
        "strengths": [
            {"pokemon_type": "Water", "percentage": 0.5},
            {"pokemon_type": "Electric", "percentage": 0.5},
            {"pokemon_type": "Grass", "percentage": 0.75},
            {"pokemon_type": "Fighting", "percentage": 0.5},
            {"pokemon_type": "Fairy", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Fire", "percentage": 2},
            {"pokemon_type": "Ice", "percentage": 2},
            {"pokemon_type": "Flying", "percentage": 2},
            {"pokemon_type": "Psychic", "percentage": 2},
        ],
    },
    {
        "name": "Venusaur",
        "hp": 364,
        "moves": [
            {"move": "Solar Beam", "move_type": "Grass", "power": 120},
            {"move": "Power Whip", "move_type": "Grass", "power": 120},
            {"move": "Petal Dance", "move_type": "Grass", "power": 120},
            {"move": "Take Down", "move_type": "Normal", "power": 90},
        ],
        "strengths": [
            {"pokemon_type": "Water", "percentage": 0.5},
            {"pokemon_type": "Electric", "percentage": 0.5},
            {"pokemon_type": "Grass", "percentage": 0.75},
            {"pokemon_type": "Fighting", "percentage": 0.5},
            {"pokemon_type": "Fairy", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Fire", "percentage": 2},
            {"pokemon_type": "Ice", "percentage": 2},
            {"pokemon_type": "Flying", "percentage": 2},
            {"pokemon_type": "Psychic", "percentage": 2},
        ],
    },
    {
        "name": "Charmander",
        "hp": 282,
        "moves": [
            {"move": "Flare Blitz", "move_type": "Fire", "power": 120},
            {"move": "Inferno", "move_type": "Fire", "power": 100},
            {"move": "Flamethrower", "move_type": "Fire", "power": 90},
            {"move": "Slash", "move_type": "Normal", "power": 70},
        ],
        "strengths": [
            {"pokemon_type": "Fire", "percentage": 0.5},
            {"pokemon_type": "Grass", "percentage": 0.5},
            {"pokemon_type": "Ice", "percentage": 0.5},
            {"pokemon_type": "Bug", "percentage": 0.5},
            {"pokemon_type": "Steel", "percentage": 0.5},
            {"pokemon_type": "Fairy", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Water", "percentage": 2},
            {"pokemon_type": "Ground", "percentage": 2},
            {"pokemon_type": "Rock", "percentage": 2},
        ],
    },
    {
        "name": "Charmeleon",
        "hp": 320,
        "moves": [
            {"move": "Flare Blitz", "move_type": "Fire", "power": 120},
            {"move": "Inferno", "move_type": "Fire", "power": 100},
            {"move": "Flamethrower", "move_type": "Fire", "power": 90},
            {"move": "Slash", "move_type": "Normal", "power": 70},
        ],
        "strengths": [
            {"pokemon_type": "Fire", "percentage": 0.5},
            {"pokemon_type": "Grass", "percentage": 0.5},
            {"pokemon_type": "Ice", "percentage": 0.5},
            {"pokemon_type": "Bug", "percentage": 0.5},
            {"pokemon_type": "Steel", "percentage": 0.5},
            {"pokemon_type": "Fairy", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Water", "percentage": 2},
            {"pokemon_type": "Ground", "percentage": 2},
            {"pokemon_type": "Rock", "percentage": 2},
        ],
    },
    {
        "name": "Charizard",
        "hp": 360,
        "moves": [
            {"move": "Flare Blitz", "move_type": "Fire", "power": 120},
            {"move": "Inferno", "move_type": "Fire", "power": 100},
            {"move": "Heat Wave", "move_type": "Fire", "power": 95},
            {"move": "Flamethrower", "move_type": "Fire", "power": 90},
        ],
        "strengths": [
            {"pokemon_type": "Fire", "percentage": 0.5},
            {"pokemon_type": "Grass", "percentage": 0.75},
            {"pokemon_type": "Fighting", "percentage": 0.5},
            {"pokemon_type": "Ground", "percentage": 0},
            {"pokemon_type": "Bug", "percentage": 0.75},
            {"pokemon_type": "Steel", "percentage": 0.5},
            {"pokemon_type": "Fairy", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Water", "percentage": 2},
            {"pokemon_type": "Electric", "percentage": 2},
            {"pokemon_type": "Rock", "percentage": 4},
        ],
    },
    {
        "name": "Squirtle",
        "hp": 292,
        "moves": [
            {"move": "Wave Crash", "move_type": "Water", "power": 120},
            {"move": "Hydro Pump", "move_type": "Water", "power": 110},
            {"move": "Aqua Tail", "move_type": "Water", "power": 90},
            {"move": "Bite", "move_type": "Dark", "power": 60},
        ],
        "strengths": [
            {"pokemon_type": "Fire", "percentage": 0.5},
            {"pokemon_type": "Water", "percentage": 0.5},
            {"pokemon_type": "Ice", "percentage": 0.5},
            {"pokemon_type": "Steel", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Electric", "percentage": 2},
            {"pokemon_type": "Grass", "percentage": 2},
        ],
    },
    {
        "name": "Wartortle",
        "hp": 322,
        "moves": [
            {"move": "Wave Crash", "move_type": "Water", "power": 120},
            {"move": "Hydro Pump", "move_type": "Water", "power": 110},
            {"move": "Aqua Tail", "move_type": "Water", "power": 90},
            {"move": "Water Pulse", "move_type": "Water", "power": 60},
        ],
        "strengths": [
            {"pokemon_type": "Fire", "percentage": 0.5},
            {"pokemon_type": "Water", "percentage": 0.5},
            {"pokemon_type": "Ice", "percentage": 0.5},
            {"pokemon_type": "Steel", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Electric", "percentage": 2},
            {"pokemon_type": "Grass", "percentage": 2},
        ],
    },
    {
        "name": "Blastoise",
        "hp": 362,
        "moves": [
            {"move": "Wave Crash", "move_type": "Water", "power": 120},
            {"move": "Hydro Pump", "move_type": "Water", "power": 110},
            {"move": "Aqua Tail", "move_type": "Water", "power": 90},
            {"move": "Water Pulse", "move_type": "Water", "power": 60},
        ],
        "strengths": [
            {"pokemon_type": "Fire", "percentage": 0.5},
            {"pokemon_type": "Water", "percentage": 0.5},
            {"pokemon_type": "Ice", "percentage": 0.5},
            {"pokemon_type": "Steel", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Electric", "percentage": 2},
            {"pokemon_type": "Grass", "percentage": 2},
        ],
    },
    {
        "name": "Caterpie",
        "hp": 294,
        "moves": [
            {"move": "Bug Bite", "move_type": "Bug", "power": 60},
            {"move": "Electroweb", "move_type": "Electric", "power": 55},
            {"move": "Snore", "move_type": "Normal", "power": 50},
            {"move": "Tackle", "move_type": "Normal", "power": 40},
        ],
        "strengths": [
            {"pokemon_type": "Grass", "percentage": 0.5},
            {"pokemon_type": "Fighting", "percentage": 0.5},
            {"pokemon_type": "Ground", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Fire", "percentage": 2},
            {"pokemon_type": "Flying", "percentage": 2},
            {"pokemon_type": "Rock", "percentage": 2},
        ],
    },
    {
        "name": "Metapod",
        "hp": 304,
        "moves": [
            {"move": "Bug Bite", "move_type": "Bug", "power": 60},
            {"move": "Electroweb", "move_type": "Electric", "power": 55},
            {"move": "Snore", "move_type": "Normal", "power": 50},
            {"move": "Tackle", "move_type": "Normal", "power": 40},
        ],
        "strengths": [
            {"pokemon_type": "Grass", "percentage": 0.5},
            {"pokemon_type": "Fighting", "percentage": 0.5},
            {"pokemon_type": "Ground", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Fire", "percentage": 2},
            {"pokemon_type": "Flying", "percentage": 2},
            {"pokemon_type": "Rock", "percentage": 2},
        ],
    },
    {
        "name": "Butterfree",
        "hp": 324,
        "moves": [
            {"move": "Bug Buzz", "move_type": "Bug", "power": 90},
            {"move": "Air Slash", "move_type": "Flying", "power": 75},
            {"move": "Psybeam", "move_type": "Psychic", "power": 65},
            {"move": "Bug Bite", "move_type": "Bug", "power": 60},
        ],
        "strengths": [
            {"pokemon_type": "Grass", "percentage": 0.75},
            {"pokemon_type": "Fighting", "percentage": 0.75},
            {"pokemon_type": "Ground", "percentage": 0},
            {"pokemon_type": "Bug", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Fire", "percentage": 2},
            {"pokemon_type": "Electric", "percentage": 2},
            {"pokemon_type": "Ice", "percentage": 2},
            {"pokemon_type": "Flying", "percentage": 2},
            {"pokemon_type": "Rock", "percentage": 4},
        ],
    },
    {
        "name": "Weedle",
        "hp": 284,
        "moves": [
            {"move": "Bug Bite", "move_type": "Bug", "power": 60},
            {"move": "Electroweb", "move_type": "Electric", "power": 55},
            {"move": "Tackle", "move_type": "Normal", "power": 40},
            {"move": "Poison Sting", "move_type": "Poison", "power": 15},
        ],
        "strengths": [
            {"pokemon_type": "Grass", "percentage": 0.75},
            {"pokemon_type": "Fighting", "percentage": 0.75},
            {"pokemon_type": "Poison", "percentage": 0.5},
            {"pokemon_type": "Bug", "percentage": 0.5},
            {"pokemon_type": "Fairy", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Fire", "percentage": 2},
            {"pokemon_type": "Flying", "percentage": 2},
            {"pokemon_type": "Psychic", "percentage": 2},
            {"pokemon_type": "Rock", "percentage": 2},
        ],
    },
    {
        "name": "Kakuna",
        "hp": 294,
        "moves": [
            {"move": "Bug Bite", "move_type": "Bug", "power": 60},
            {"move": "Electroweb", "move_type": "Electric", "power": 55},
            {"move": "Tackle", "move_type": "Normal", "power": 40},
            {"move": "Poison Sting", "move_type": "Poison", "power": 15},
        ],
        "strengths": [
            {"pokemon_type": "Grass", "percentage": 0.75},
            {"pokemon_type": "Fighting", "percentage": 0.75},
            {"pokemon_type": "Poison", "percentage": 0.5},
            {"pokemon_type": "Bug", "percentage": 0.5},
            {"pokemon_type": "Fairy", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Fire", "percentage": 2},
            {"pokemon_type": "Flying", "percentage": 2},
            {"pokemon_type": "Psychic", "percentage": 2},
            {"pokemon_type": "Rock", "percentage": 2},
        ],
    },
    {
        "name": "Beedrill",
        "hp": 334,
        "moves": [
            {"move": "Poison Jab", "move_type": "Poison", "power": 80},
            {"move": "Venoshock", "move_type": "Poison", "power": 65},
            {"move": "Assurance", "move_type": "Dark", "power": 60},
            {"move": "Bug Bite", "move_type": "Bug", "power": 60},
        ],
        "strengths": [
            {"pokemon_type": "Grass", "percentage": 0.75},
            {"pokemon_type": "Fighting", "percentage": 0.75},
            {"pokemon_type": "Poison", "percentage": 0.5},
            {"pokemon_type": "Bug", "percentage": 0.5},
            {"pokemon_type": "Fairy", "percentage": 0.5},
        ],
        "weaknesses": [
            {"pokemon_type": "Fire", "percentage": 2},
            {"pokemon_type": "Flying", "percentage": 2},
            {"pokemon_type": "Psychic", "percentage": 2},
            {"pokemon_type": "Rock", "percentage": 2},
        ],
    },
]
